

export default {
    SUCCESS: `The operation has been successful`,
    SOMETHING_WENT_WRONG: `Something went wrong`,
    NOT_FOUND: (entity:string)=> `${entity} not found` ,
    TOO_MANY_REQUEST: `Too many requests! Please try agaion after some time.`,
    UNAUTHORIZED: `You are not authorized to perform this action`,
    INVALID_CREDENTIALS: `Invalid credentials`,
    USER_ALREADY_EXISTS: `User already exists`,
    USER_NOT_FOUND: `User not found`,
    INVALID_TOKEN: `Invalid token`,
    TOKEN_EXPIRED: `Token expired`,
    INVALID_PASSWORD: `Invalid password`,
    PASSWORD_DOES_NOT_MATCH: `Password does not match`,
    INVALID_EMAIL: `Invalid email`,
    EMAIL_ALREADY_EXISTS: `Email already exists`,
    INVALID_PHONE: `Invalid phone number`,
    PHONE_ALREADY_EXISTS: `Phone number already exists`,
    INVALID_OTP: `Invalid OTP`,
    OTP_EXPIRED: `OTP expired`,
    INVALID_CODE: `Invalid code`,
    CODE_EXPIRED: `Code expired`,
    INVALID_USERNAME: `Invalid username`,
    USERNAME_ALREADY_EXISTS: `Username already exists`,
    INVALID_NAME: `Invalid name`,
    NAME_ALREADY_EXISTS: `Name already exists`,
    ALREADY_VERIFIED: `User is already verified`, 
    NOT_VERIFIED: `User is not verified`,
    INVALID_DATE: `Invalid date`,
    USER_LOGGED_OUT: `User has been logged out`   
}